{{- $root := . -}}
{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "symbia.fullname" $root }}-{{ $serviceName }}
  labels:
    {{- include "symbia.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $serviceName }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
{{- end }}
{{- end }}
